apiVersion: v1
kind: Namespace
metadata:
  name: dsassenger-namespace
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: flask-deployment
    namespace: dsassenger-namespace
    labels:
      app: flask
spec:
   replicas: 2
   selector: 
    matchLabels:
        app: flask
    template:
      metadata:
        labels:
          app: flask
      spec:
        containers:
        - name: flask
          image: dsassenger/flask
          ports:
          - containerPort: 5000
          imagePullpolicy: Always

---
  